---
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

env:
  - CXX=g++-4.8 WORKER_COUNT=2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

cache:
  yarn: true

before_install:
  # Once we no longer support Node.js 0.12 we can drop this entire section.
  # prevent the npm loading indicator
  - npm config --global set spin false
  # if npm version is less than 3.0.0, upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi
  - npm i -g phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn

script:
  - yarn run test
