---
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

env:
  - CXX=g++-4.8 WORKER_COUNT=2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

cache:
  yarn: true

before_install:
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn

script:
  - yarn run test
